apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  ports:
    - port: 8000
  selector:
    app: jupyterhub
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  selector:
    matchLabels:
      app: jupyterhub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - image: sxzhang/jupyterhub:1.0
        name: jupyterhub
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: jupyterhub-persistent-storage
        nfs:
          server: <nfs-server>
          path: "/notebooks"
